refactor(selenium): Import `execaCommand` instead of `execa.command`
Not sure why the previous way was causing a type error after switching to pnpm:

```
Error: src/selenium.ts(84,17): error TS2339: Property 'command' does not exist
on type 'typeof import("/home/runner/work/tdd-buffet/tdd-buffet/node_modules/.pnpm/execa@6.0.0/node_modules/execa/index")'.
```